server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopping
    username: root
    password: root

  # data.sql 파일의 초기 데이터를 삽입한다.
  sql:
    init:
      mode: never
      encoding: utf-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # EntityManagerFactory Bean 을 생성하고 초기화를 마칠 때 까지 DataSource 초기화를 미룬다.
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true