spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1096071535998-30tgst0i7le5rf4eh5l0h1mindp5p51h.apps.googleusercontent.com
            client-secret: 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
            scope: 
            - email
            - profile
            
          kakao:
            client-id: b2ca4671ce30132e5afaa717d858878f
            client-secret: o7bNyouYXvaKvVnw2njRs10Fuevhp03U
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
            - profile_nickname
            - profile_image
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            
            
            
            
            
            
            
            